name : Rust learn Action

on :
  push :
    branches : [ "main" ]
  workflow_dispatch:

env :
  RUST_INSTALL_VERSION : stable

#  CREATES_TOKEN : ${{ secret.CREATES_REGISTRY }} # Create.io Account Token
#  GITHUB_REPO   : ${{ github.ref }}

jobs:
  Setup:
    runs-on  : self-hosted
    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name : Install Rust Toolchain
        uses : actions-rust-lang/setup-rust-toolchain@v1 # Why need use the Rust Toolchain?
        with :
          toolchain : ${{ env.RUST_INSTALL_VERSION }} # Default Toolchain : Stable [OK]
