name : Rust learn Action

on :
  push :
    branches : [ "main" ]
    paths    : [ "../src/bin/*", "../Cargo.toml" ]

env :
  RUST_VERSION : nightly
  RUN_FILES : "./src/bin/*"

jobs:
  Setup:
    runs-on : ubuntu-latest
    steps :
      - name : Checkout
        uses : actions/checkout@v4

      - name : Install Rust Toolchain
        uses : actions-rs/toolchain@v1
        with :
          toolchain : ${{ env.RUST_VERSION }}
        run  : |
          cargo clean &&\
          cargo build &&\
          time cargo check

      - name : Learn Bin Cargo run
        run : |
          cargo run --bin ${{ env.RUN_FILES }}
