name : Rust learn Action

on :
  push :
    branches : [ "main" ]
    paths    : [ "./src/bin/*" ]
  workflow_dispatch:

jobs:
  Setup:
    runs-on : self-hosted
    steps :
      - name : Checkout
        uses : actions/checkout@v4

      - name : Install Rust Toolchain
        uses : actions-rust-lang/setup-rust-toolchain@v1  # Waring : Uses와 Run을 함께 사용하지 못한다.

      - name : Learn Bin Cargo run
        run: |
          find ./src/bin -type f -executable | xargs -I {} basename {} | xargs -I {} cargo run --bin {}